kind: Service
apiVersion: v1
metadata:
  name: mycompany-monolith-svr
spec:
  ports:
    - port: 8080 
      targetPort: 8080
      nodePort: 30080
  selector:
    component: mycompany-monolith
  type: NodePort
