
---
# Default settings

microservicesMode: false

ServiceB:
  ribbon:
    listOfServers: localhost:8080
ServiceD:
  ribbon:
    listOfServers: localhost:8080
---

spring:
  profiles: microservices
  
microservicesMode: true

ServiceA:
  ribbon:
    listOfServers: service-a:8080
ServiceB:
  ribbon:
    listOfServers: service-b:8080
ServiceC:
  ribbon:
    listOfServers: service-c:8080
ServiceD:
  ribbon:
    listOfServers: service-d:8080
 
